#!/usr/bin/env bash

echo "== delete object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. bucket my-bucket-name"
    exit 1;
fi

BUCKET_NAME=$1

aws s3api delete-object --bucket $BUCKET_NAME