#!/usr/bin/env bash

echo "== create bucket"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. bucket my-bucket-name"
    exit 1;
fi

BUCKET_NAME=$1

echo "aws s3api create-bucket --bucket $BUCKET_NAME"

aws s3api create-bucket --bucket my-new-aman-an --region us-east-1 --query Location --output text

